#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum OpCode {
    Constant = 0,
    Nil,
    True,
    False,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Negate,
    Not,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Equal,
    NotEqual,
    Pop,
    GetGlobal,
    SetGlobal,
    GetLocal,
    SetLocal,
    JumpIfFalse,
    JumpIfFalseKeep,
    JumpIfTrueKeep,
    Jump,
    Call,
    Return,
    NewStruct,
    GetField,
    SetField,
    NewSlice,
    NewMap,
    GetIndex,
    SetIndex,
    CallMethod,
}

impl OpCode {
    pub fn name(&self) -> &'static str {
        match self {
            OpCode::Constant => "Constant",
            OpCode::Nil => "Nil",
            OpCode::True => "True",
            OpCode::False => "False",
            OpCode::Add => "Add",
            OpCode::Sub => "Sub",
            OpCode::Mul => "Mul",
            OpCode::Div => "Div",
            OpCode::Mod => "Mod",
            OpCode::Negate => "Negate",
            OpCode::Not => "Not",
            OpCode::Greater => "Greater",
            OpCode::GreaterEqual => "GreaterEqual",
            OpCode::Less => "Less",
            OpCode::LessEqual => "LessEqual",
            OpCode::Equal => "Equal",
            OpCode::NotEqual => "NotEqual",
            OpCode::Pop => "Pop",
            OpCode::GetGlobal => "GetGlobal",
            OpCode::SetGlobal => "SetGlobal",
            OpCode::GetLocal => "GetLocal",
            OpCode::SetLocal => "SetLocal",
            OpCode::JumpIfFalse => "JumpIfFalse",
            OpCode::JumpIfFalseKeep => "JumpIfFalseKeep",
            OpCode::JumpIfTrueKeep => "JumpIfTrueKeep",
            OpCode::Jump => "Jump",
            OpCode::Call => "Call",
            OpCode::Return => "Return",
            OpCode::NewStruct => "NewStruct",
            OpCode::GetField => "GetField",
            OpCode::SetField => "SetField",
            OpCode::NewSlice => "NewSlice",
            OpCode::NewMap => "NewMap",
            OpCode::GetIndex => "GetIndex",
            OpCode::SetIndex => "SetIndex",
            OpCode::CallMethod => "CallMethod",
        }
    }
}

impl From<u8> for OpCode {
    fn from(byte: u8) -> Self {
        match byte {
            0 => OpCode::Constant,
            1 => OpCode::Nil,
            2 => OpCode::True,
            3 => OpCode::False,
            4 => OpCode::Add,
            5 => OpCode::Sub,
            6 => OpCode::Mul,
            7 => OpCode::Div,
            8 => OpCode::Mod,
            9 => OpCode::Negate,
            10 => OpCode::Not,
            11 => OpCode::Greater,
            12 => OpCode::GreaterEqual,
            13 => OpCode::Less,
            14 => OpCode::LessEqual,
            15 => OpCode::Equal,
            16 => OpCode::NotEqual,
            17 => OpCode::Pop,
            18 => OpCode::GetGlobal,
            19 => OpCode::SetGlobal,
            20 => OpCode::GetLocal,
            21 => OpCode::SetLocal,
            22 => OpCode::JumpIfFalse,
            23 => OpCode::JumpIfFalseKeep,
            24 => OpCode::JumpIfTrueKeep,
            25 => OpCode::Jump,
            26 => OpCode::Call,
            27 => OpCode::Return,
            28 => OpCode::NewStruct,
            29 => OpCode::GetField,
            30 => OpCode::SetField,
            31 => OpCode::NewSlice,
            32 => OpCode::NewMap,
            33 => OpCode::GetIndex,
            34 => OpCode::SetIndex,
            35 => OpCode::CallMethod,
            other => unreachable!("invalid opcode byte {other}"),
        }
    }
}